site_name: Banco de Dados
site_author: Maria Gabriela Santos
site_url: https://hsandmann.github.io/ml
repo_url: https://github.com/hsandmann/ml
repo_name: hsandmann/ml

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: green
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
  
  font:
    text: Roboto
    code: Fira Code

  features:
    - navigation.tabs
    - tags
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.path
    - navigation.tracking
  icon:
    # logo: assets/images/devops
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  logo: assets/images/logo.png

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - md_in_html
  - markdown_grid_tables:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.blocks.caption
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - neoteroi.timeline
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true


plugins:
  - awesome-pages
  - mermaid2
  - table-reader
  - mkdocs-jupyter
  - glightbox
  - include-markdown
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
  - git-committers:
      repository: insper/ann-dl
      branch: main
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY
  - search
  - minify:
      minify_html: true
  - badges
  - markdown-exec
  - mkdocs-pdf
  - render_swagger:
      allow_arbitrary_locations : true
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/stylesheets/neoteroi-mkdocs.min.css
  - assets/stylesheets/neoteroi-timeline.css
  - assets/stylesheets/extra.css


nav:

  - 2025.2: ./versions/2025.2/main.md
  - Aulas:
    - 1. Concepts:
      - 1.1. Machine Learning: ./classes/concepts/ml/ml.md
      - 1.2. KDD: ./classes/concepts/kdd/kdd.md
      - 1.3. Data: ./classes/concepts/data/data.md
      - 1.4. Exercise: ./classes/concepts/exercise/exercise.md
    - 2. Decision Tree: ./classes/decision_tree/decision_tree.md
    - 3. Preprocessing: ./classes/preprocessing/preprocessing.md
    - 4. KNN: ./classes/knn/knn.md
    - 5. K-Means: ./classes/kmeans/kmeans.md
    - 6. Evaluation Metrics: ./classes/metrics/metricas.md
    - 7. Random Forest: ./classes/random_forest/random_forest.md
    - 8. SVM: ./classes/svm/svm.md
    - 9. Page Rank: ./classes/page_rank/page_rank.md
    - 10. PySpark: ./classes/pyspark/pyspark.md

  - Projetos:
    - Projeto I: ./versions/2025.2/projects/1/projeto_i.md
    - Projeto II: ./versions/2025.2/projects/2/projeto_ii.md

  - Versões:
    - 2025.2: ./versions/2025.2/main.md
